<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="MSTest" />
    <PackageReference Include="Testcontainers.PostgreSql" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <PackageReference Include="Respawn" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Microsoft.VisualStudio.TestTools.UnitTesting" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/RecipeJoe.Api/RecipeJoe.Api.csproj" />
  </ItemGroup>

</Project>
