<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="MSTest" />
    <PackageReference Include="Testcontainers.PostgreSql" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <PackageReference Include="Respawn" />
    <PackageReference Include="WireMock.Net" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Microsoft.VisualStudio.TestTools.UnitTesting" />
  </ItemGroup>

  <ItemGroup>
    <None Include="../../../fixtures/**" Link="fixtures/%(RecursiveDir)%(Filename)%(Extension)" CopyToOutputDirectory="PreserveNewest" />
    <Compile Include="../RecipeJoe.UnitTests/Import/FixturePageFetcher.cs" Link="FixturePageFetcher.cs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/RecipeJoe.Api/RecipeJoe.Api.csproj" />
  </ItemGroup>

</Project>
