/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/imports': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['ListImports'];
    put?: never;
    post: operations['StartImport'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/imports/{id}/retry': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['RetryImport'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/imports/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete: operations['DismissImport'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/recipes': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['ListRecipes'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/recipes/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['GetRecipe'];
    put?: never;
    post?: never;
    delete: operations['DeleteRecipe'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/recipes/{id}/image': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['GetRecipeImage'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    ImportDto: {
      /** Format: uuid */
      id: string;
      url: string;
      kind: components['schemas']['ImportKind'];
      state: components['schemas']['ImportState'];
      stage: null | components['schemas']['ImportStage'];
      failure: null | components['schemas']['ImportFailure'];
    };
    /** @enum {unknown} */
    ImportFailure:
      | 'InvalidUrl'
      | 'Unreachable'
      | 'Blocked'
      | 'NotFound'
      | 'BadResponse'
      | 'ForbiddenAddress'
      | 'NoRecipe'
      | 'NoCaptions'
      | 'LlmUnavailable'
      | 'LlmBadOutput'
      | 'VideoTooLong'
      | 'SaveFailed'
      | null;
    /** @enum {unknown} */
    ImportKind: 'Web' | 'Video';
    ImportsProblem: {
      type: string;
      title: string;
      /** Format: int32 */
      status: number;
      kind: components['schemas']['ImportFailure'];
    };
    /** @enum {unknown} */
    ImportStage: 'Fetching' | 'Extracting' | 'Saving' | null;
    /** @enum {unknown} */
    ImportState: 'Pending' | 'Failed';
    RecipeDto: {
      /** Format: int32 */
      id: number;
      title: string;
      servings: null | string;
      /** Format: int32 */
      prepMinutes: null | number;
      /** Format: int32 */
      cookMinutes: null | number;
      /** Format: int32 */
      totalMinutes: null | number;
      ingredientLines: string[];
      steps: string[];
      sourceUrl: string;
      imageUrl: null | string;
      /** Format: date-time */
      createdAt: string;
    };
    RecipeSummaryDto: {
      /** Format: int32 */
      id: number;
      title: string;
      sourceUrl: string;
      hasImage: boolean;
      isNew: boolean;
    };
    StartImportRequest: {
      url: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  ListImports: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ImportDto'][];
        };
      };
    };
  };
  StartImport: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['StartImportRequest'];
      };
    };
    responses: {
      /** @description Accepted */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ImportDto'];
        };
      };
      /** @description Bad Request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ImportsProblem'];
        };
      };
    };
  };
  RetryImport: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Accepted */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ImportDto'];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  DismissImport: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description No Content */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  ListRecipes: {
    parameters: {
      query?: {
        q?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['RecipeSummaryDto'][];
        };
      };
    };
  };
  GetRecipe: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['RecipeDto'];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  DeleteRecipe: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description No Content */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  GetRecipeImage: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'image/jpeg': string;
          'image/png': string;
          'image/webp': string;
          'image/gif': string;
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
}
