// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RecipeJoe.Api;

#nullable disable

namespace RecipeJoe.Api.Migrations
{
    [DbContext(typeof(RecipeJoeDbContext))]
    [Migration("20261001115651_AddRecipeSeenAt")]
    partial class AddRecipeSeenAt
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RecipeJoe.Api.Images.RecipeImage", b =>
                {
                    b.Property<int>("RecipeId")
                        .HasColumnType("integer");

                    b.Property<byte[]>("Bytes")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("RecipeId");

                    b.ToTable("RecipeImages", (string)null);
                });

            modelBuilder.Entity("RecipeJoe.Api.Recipes.Recipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<TimeSpan?>("CookTime")
                        .HasColumnType("interval");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<TimeSpan?>("PrepTime")
                        .HasColumnType("interval");

                    b.Property<DateTimeOffset?>("SeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Servings")
                        .HasColumnType("text");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<TimeSpan?>("TotalTime")
                        .HasColumnType("interval");

                    b.HasKey("Id");

                    b.ToTable("Recipes");
                });

            modelBuilder.Entity("RecipeJoe.Api.Images.RecipeImage", b =>
                {
                    b.HasOne("RecipeJoe.Api.Recipes.Recipe", null)
                        .WithOne("Image")
                        .HasForeignKey("RecipeJoe.Api.Images.RecipeImage", "RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RecipeJoe.Api.Recipes.Recipe", b =>
                {
                    b.OwnsMany("RecipeJoe.Api.Recipes.IngredientLine", "IngredientLines", b1 =>
                        {
                            b1.Property<int>("RecipeId")
                                .HasColumnType("integer");

                            b1.Property<int>("Position")
                                .HasColumnType("integer");

                            b1.Property<string>("Text")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("RecipeId", "Position");

                            b1.ToTable("IngredientLines", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("RecipeId");
                        });

                    b.OwnsMany("RecipeJoe.Api.Recipes.Step", "Steps", b1 =>
                        {
                            b1.Property<int>("RecipeId")
                                .HasColumnType("integer");

                            b1.Property<int>("Position")
                                .HasColumnType("integer");

                            b1.Property<string>("Text")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("RecipeId", "Position");

                            b1.ToTable("Steps", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("RecipeId");
                        });

                    b.Navigation("IngredientLines");

                    b.Navigation("Steps");
                });

            modelBuilder.Entity("RecipeJoe.Api.Recipes.Recipe", b =>
                {
                    b.Navigation("Image");
                });
#pragma warning restore 612, 618
        }
    }
}
