using System.Net;
using RecipeJoe.Api.Import;
using YoutubeExplode.Exceptions;
using YoutubeExplode.Videos.ClosedCaptions;

namespace RecipeJoe.Api.Video;

/// <summary>The pure decisions of the YouTube adapter, kept apart from the network: which caption track to read, how it becomes a transcript, and which <see cref="ImportFailure"/> a library error means.</summary>
internal static class YouTubeCaptions
{
    /// <summary>Manual over auto-generated; the first listed wins, which is the original language (YouTube lists the spoken language's ASR first). No auto-translation, the LLM writes German anyway.</summary>
    public static ClosedCaptionTrackInfo? ChooseTrack(IReadOnlyList<ClosedCaptionTrackInfo> tracks) =>
        tracks.FirstOrDefault(t => !t.IsAutoGenerated) ?? (tracks.Count > 0 ? tracks[0] : null);

    public static string ToTranscript(IEnumerable<string> captionTexts) =>
        string.Join('\n', captionTexts.Select(t => t.Trim()).Where(t => t.Length > 0));

    /// <summary>Null for exceptions that aren't YouTube trouble (bugs, cancellation) and should keep propagating.</summary>
    public static ImportFailure? MapFailure(Exception exception) =>
        exception switch
        {
            HttpRequestException { StatusCode: HttpStatusCode.Forbidden or HttpStatusCode.TooManyRequests } => ImportFailure.Blocked,
            HttpRequestException => ImportFailure.Unreachable,
            RequestLimitExceededException => ImportFailure.Blocked,
            VideoUnavailableException or VideoUnplayableException or VideoRequiresPurchaseException => ImportFailure.NotFound,
            YoutubeExplodeException => ImportFailure.BadResponse,
            _ => null,
        };
}
